// <auto-generated />
namespace Sh4dow.RefuellingHistory.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsFullRefuellAddedToRefuelling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsFullRefuellAddedToRefuelling));
        
        string IMigrationMetadata.Id
        {
            get { return "201510151124489_IsFullRefuellAddedToRefuelling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
